[[master]]
  ip = "192.168.1.1"
  port = 22
  user = "root"
  passwd = "password"

[[master]]
  ip = "192.168.1.2"
  port = 22
  user = "root"
  passwd = "password"

[[client]]
  ip = "192.168.1.3"
  port = 22
  user = "root"
  passwd = "password"

[[client]]
  ip = "192.168.1.4"
  port = 22
  user = "root"
  passwd = "password"
